#  ::::::::::: :::     :::::::::  :::::::::: :::::::::   ::::::::  :::   ::: ::::    :::  ::::::::
#      :+:   :+: :+:   :+:    :+: :+:        :+:    :+: :+:    :+: :+:   :+: :+:+:   :+: :+:    :+:
#      +:+  +:+   +:+  +:+    +:+ +:+        +:+    +:+ +:+         +:+ +:+  :+:+:+  +:+ +:+
#      +#+ +#++:++#++: +#+    +:+ +#++:++#   +#+    +:+ +#++:++#++   +#++:   +#+ +:+ +#+ +#+
#      +#+ +#+     +#+ +#+    +#+ +#+        +#+    +#+        +#+    +#+    +#+  +#+#+# +#+
#  #+# #+# #+#     #+# #+#    #+# #+#        #+#    #+# #+#    #+#    #+#    #+#   #+#+# #+#    #+#
#   #####  ###     ### #########  ########## #########   ########     ###    ###    ####  ########
#
#  Version ${project.version}
#  By JadedMC

file-version: 1

# The connection information for the Redis server.
# Once set, make "set" true.
Redis:
  host: "127.0.0.1"
  port: 6379
  username: ""
  password: ""
  set: false